spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:db-sharding.yaml
    hikari:
      pool-name: user-pool
      minimum-idle: 15
      idle-timeout: 60000
      maximum-pool-size: 300
      connection-init-sql: SELECT 1
      connection-timeout: 4000
      max-lifetime: 60000
  data:
    redis:
      port: 6379
      host: live-server
      lettuce:
        pool:
          min-idle: 10
          max-idle: 20
          max-active: 50

rmq:
  producer:
    nameSrv: live-server:9876
    groupName: ${spring.application.name}
    retryTimes: 3
    sendTimeOut: 3000
  consumer:
    nameSrv: live-server:9876
    groupName: ${spring.application.name}


dubbo:
  application:
    name: live-user-provider
  registry:
    address: nacos://live-server:8848?namespace=live-test&&username=nacos&&password=nacos
  protocol:
    name: dubbo
    port: 9091


