dubbo.application.name=live-user-provider
dubbo.registry.address=nacos://live-server:8848?namespace=live-test&&username=nacos&&password=nacos
#dubbo.registry.register-mode=instance
dubbo.server=true
dubbo.protocol.name=dubbo
dubbo.protocol.port=9090