version: '3'
services:
  live-id-generate-provider-1:
    container_name: live-account-provider-1
    image: 'live-account-provider-docker:1.0'
    ports:
      - "9098:9098"
    volumes:
      - /tmp/logs/live-account-provider:/tmp/logs/live-account-provider
    environment:
      - DUBBO_IP_TO_REGISTRY=192.168.0.254
      - DUBBO_PORT_TO_REGISTRY=9098
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms512m -Xmx512m -Xmn128m -Xss256k
    extra_hosts:
      - 'live-server:192.168.0.254'