version: '3'
services:
  live-id-generate-provider-1:
    container_name: live-im-provider-1
    image: 'live-im-provider-docker:1.0'
    ports:
      - "9010:9010"
    volumes:
      - /tmp/logs/live-im-provider:/tmp/logs/live-im-provider
    environment:
      - DUBBO_IP_TO_REGISTRY=192.168.1.7
      - DUBBO_PORT_TO_REGISTRY=9010
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms512m -Xmx512m -Xmn128m -Xss256k
    extra_hosts:
      - 'live-server:192.168.0.254'